# Generated by Django 4.0.3 on 2022-12-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noksha', '0002_category_img_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebannercategory',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='homebannercategory',
            name='sub_title_heading',
        ),
    ]
