# Generated by Django 4.0.3 on 2022-12-25 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noksha', '0003_remove_homebannercategory_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_for', models.CharField(blank=True, max_length=200, null=True)),
                ('categorys', models.ManyToManyField(to='noksha.subcategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
