# Generated by Django 4.0.3 on 2022-12-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noksha', '0004_popularfurniture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
        migrations.RemoveField(
            model_name='collectioncategory',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='collectioncategory',
            name='sub_heading',
        ),
    ]
