# Generated by Django 4.0.3 on 2022-12-25 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noksha', '0005_remove_category_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopnowcategorys',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='shopnowcategorys',
            name='title',
        ),
        migrations.AlterField(
            model_name='shopnowcategorys',
            name='estimated_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noksha.subcategory'),
        ),
    ]
