# Generated by Django 4.0.3 on 2022-12-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noksha', '0006_remove_shopnowcategorys_sub_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopnowcategorys',
            name='category_for',
        ),
    ]
