# Generated by Django 4.0.3 on 2022-12-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noksha', '0007_remove_shopnowcategorys_category_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ManyToManyField(to='noksha.subcategory'),
        ),
    ]
